blend.clrwl_gbuffers = off
blend.clrwl_gbuffers_glint = off
blend.clrwl_gbuffers_translucent = off
blend.clrwl_shadow = off

#if MC_VERSION > 12111
blend.clrwl_gbuffers_glint.colortex13 = ONE ONE ZERO ONE
#else
blend.clrwl_gbuffers_glint = off
blend.clrwl_gbuffers_damagedblock = off
#endif

blend.clrwl_gbuffers_translucent.colortex13 = ONE ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA

oit = true

oit.gbuffers.coefficientRanks = 3

oit.gbuffers.colortex13 = 0
oit.gbuffers.colortex13.format = RGBA16F
